disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Micah Oevermann"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "Hi I'm Micah! "

[author]
name = "Micah Oevermann"
headline = "Design, Dynamics and Mechatronics Engineer"
bio = "This is my bio in othe languages.en params file"

["params.author"]
bio = ""
